# Generated by Django 3.1.7 on 2021-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookaTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Enter your email', max_length=100, null=True)),
                ('phone', models.IntegerField(help_text='Enter your phone number', null=True)),
                ('Date', models.DateField(auto_now_add=True, help_text='Date')),
                ('Time', models.TimeField(auto_now_add=True, help_text='Time')),
                ('number_of_people', models.IntegerField(help_text='Enter number of people', null=True)),
                ('message', models.TextField(help_text='Description', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Enter your email', max_length=100, null=True)),
                ('subject', models.CharField(help_text='Subject', max_length=200, null=True)),
                ('message', models.TextField(help_text='Description', max_length=1000, null=True)),
            ],
        ),
    ]
