# Generated by Django 3.1.7 on 2021-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_drop_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookatable',
            name='phone',
            field=models.CharField(help_text='Enter your phone number', max_length=10, null=True),
        ),
    ]
